# Generated by Django 6.1.1 on 2026-09-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Screening', 'Screening'), ('Interview', 'Interview'), ('Tchnical Round', 'Technical Round'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('job_url', models.URLField(blank=True)),
                ('date_applied', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
